# Generated by Django 3.0.6 on 2021-08-16 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 14, 12, 50, 475789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.CharField(max_length=32),
        ),
    ]
