# Generated by Django 3.0.6 on 2021-10-07 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0004_auto_20210819_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 7, 13, 50, 23, 130923, tzinfo=utc)),
        ),
    ]
