# Generated by Django 3.0.6 on 2021-10-18 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0006_auto_20211014_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 18, 12, 54, 57, 378525, tzinfo=utc)),
        ),
    ]
