# Generated by Django 3.0.6 on 2021-11-26 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0007_auto_20211018_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 26, 15, 3, 52, 296227, tzinfo=utc)),
        ),
    ]
