# Generated by Django 3.0.6 on 2021-12-08 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0010_auto_20211208_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 8, 14, 31, 3, 399027, tzinfo=utc)),
        ),
    ]
