# Generated by Django 3.0.6 on 2021-12-10 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0013_auto_20211208_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 13, 50, 22, 470178, tzinfo=utc)),
        ),
    ]
