# Generated by Django 3.0.6 on 2021-12-13 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TDV', '0014_auto_20211210_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 14, 29, 33, 832917, tzinfo=utc)),
        ),
    ]
