# Generated by Django 3.0.6 on 2021-05-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersdb',
        ),
    ]
