# Generated by Django 3.0.6 on 2021-07-09 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 11, 37, 57, 780582)),
        ),
    ]
