# Generated by Django 3.0.6 on 2021-07-14 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0004_auto_20210713_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 11, 8, 53, 767103)),
        ),
        migrations.AlterField(
            model_name='msa',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
