# Generated by Django 3.0.6 on 2021-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0006_auto_20210714_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='time',
            field=models.DateTimeField(blank=True, default='2021-July-14 11:28:01'),
        ),
    ]
