# Generated by Django 3.0.6 on 2021-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0008_auto_20210714_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
