# Generated by Django 3.0.6 on 2021-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0012_auto_20210714_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='time',
            field=models.DateTimeField(blank=True, default='12:01:54'),
        ),
    ]
