# Generated by Django 3.0.6 on 2021-07-14 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0013_auto_20210714_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 12, 2, 47, 306414)),
        ),
    ]
