# Generated by Django 3.0.6 on 2021-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0017_auto_20210715_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='msa',
            name='room',
            field=models.IntegerField(default=1),
        ),
    ]
