# Generated by Django 3.0.6 on 2021-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0018_msa_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='r_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.IntegerField()),
                ('request_to', models.IntegerField()),
            ],
        ),
    ]
