# Generated by Django 3.0.6 on 2021-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0019_r_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_request',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
