# Generated by Django 3.0.6 on 2021-07-28 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0020_r_request_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='msa',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 12, 24, 56, 707042)),
        ),
    ]
