# Generated by Django 3.0.6 on 2021-07-30 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0025_auto_20210728_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_request',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 13, 50, 58, 602775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='msa',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 13, 50, 58, 602775, tzinfo=utc)),
        ),
    ]
