# Generated by Django 3.0.6 on 2021-08-16 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0027_auto_20210816_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 14, 12, 50, 473792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='r_request',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 14, 12, 50, 473792, tzinfo=utc)),
        ),
    ]
