# Generated by Django 3.0.6 on 2022-01-26 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messageapp', '0043_auto_20220126_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msa',
            name='time',
        ),
        migrations.AlterField(
            model_name='msa',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageapp.r_request'),
        ),
        migrations.AlterField(
            model_name='msa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='r_request',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_request_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='r_request',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_request_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
