# Generated by Django 3.0.6 on 2022-02-07 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messageapp', '0044_auto_20220126_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend_friendlist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_friendlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
