# Generated by Django 3.0.6 on 2022-02-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0045_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='Friend',
            new_name='friend',
        ),
    ]
