# Generated by Django 4.0.2 on 2022-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0047_msa_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_request',
            name='new_messages',
            field=models.BooleanField(default=False),
        ),
    ]
