# Generated by Django 3.0.6 on 2021-10-18 12:54

import TG2A.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TG2A', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', validators=[TG2A.validators.validate_file_size]),
        ),
    ]
