# Generated by Django 3.0.6 on 2021-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TG2A', '0002_auto_20211018_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
