# Generated by Django 3.0.6 on 2021-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TG2A', '0003_gallery_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
