# Generated by Django 4.0.2 on 2022-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TG2A', '0006_gallery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=64)),
                ('more_info', models.CharField(max_length=64)),
            ],
        ),
    ]
