# Generated by Django 4.0.2 on 2022-08-11 15:48

import TG2A.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TG2A', '0007_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', validators=[TG2A.validators.validate_file_size]),
        ),
    ]
